---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Jellyfin:
        href: http://192.168.4.10:8096/
        description: Stream Movies & TV

